AllCops:
  Exclude:
    # Ignore HTML related things
    - '**/*.erb'
    # Ignore vendored gems
    - 'vendor/**/*'
    # Ignore code from test fixtures
    - 'spec/fixtures/**/*'
Lint/ConditionPosition:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Style/SpaceBeforeComment:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/AndOr:
  Enabled: false
